version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
jobs:
  build:
    docker:
      - image: circleci/node:15
    environment:
      DATABASE_URI: process.env.URL
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - coveralls/upload
notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=${process.env.COVERALLS_REPO_TOKEN}